// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/gsim.h"
#include <Rcpp.h>

using namespace Rcpp;

// by_sim_impl
SEXP by_sim_impl(const List sims, NumericVector data_lengths, int n_sims, const SEXP fun, const Environment calling_env);
RcppExport SEXP gsim_by_sim_impl(SEXP simsSEXP, SEXP data_lengthsSEXP, SEXP n_simsSEXP, SEXP funSEXP, SEXP calling_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List >::type sims(simsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type data_lengths(data_lengthsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type fun(funSEXP);
    Rcpp::traits::input_parameter< const Environment >::type calling_env(calling_envSEXP);
    __result = Rcpp::wrap(by_sim_impl(sims, data_lengths, n_sims, fun, calling_env));
    return __result;
END_RCPP
}
