# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_matrix_impl <- function(data) {
    .Call('gsim_as_matrix_impl', PACKAGE = 'gsim', data)
}

find_names <- function(call) {
    .Call('gsim_find_names', PACKAGE = 'gsim', call)
}

by_sim_impl <- function(sims, data_dims, n_sims, fun, eval_env, dots) {
    .Call('gsim_by_sim_impl', PACKAGE = 'gsim', sims, data_dims, n_sims, fun, eval_env, dots)
}

