# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

by_sim_impl <- function(sims, data_lengths, n_sims, fun, calling_env) {
    .Call('gsim_by_sim_impl', PACKAGE = 'gsim', sims, data_lengths, n_sims, fun, calling_env)
}

